spring:
  datasource:
    password: 123456
    url: jdbc:postgresql://localhost:5432/Book
    username: postgres
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
#      validate: проверяет схему, не вносит изменений в базу данных.
#      update: обновить схему.
#      create: создает схему, уничтожая предыдущие данные.
#      create-drop: удалить схему в конце сеанса
#      none: все остальные случаи.
