version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "Book"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    build:
      context: docker
      dockerfile: C:\Users\User\Desktop\java Projects\bookrepository\docker\Dockerfile