create sequence hibernate_sequence start 1 increment 1;
create table author
(
    id   int8 generated by default as identity,
    name varchar(255),
    primary key (id)
);
create table author_genre
(
    author_id int8 not null,
    genre_id  int4 not null,
    primary key (author_id, genre_id)
);
create table book
(
    id    int8 generated by default as identity,
    name  varchar(255),
    price int4,
    primary key (id)
);
create table book_author
(
    author_id int8 not null,
    book_id   int8 not null,
    primary key (author_id, book_id)
);
create table genre
(
    id   int4 generated by default as identity,
    name varchar(255),
    primary key (id)
);
alter table if exists author_genre add constraint author_genre_genre_id foreign key (genre_id) references genre;
alter table if exists author_genre add constraint author_genre_author_id foreign key (author_id) references author;
alter table if exists book_author add constraint book_author_book_id foreign key (book_id) references author;
alter table if exists book_author add constraint book_author_author_id foreign key (author_id) references book;