create table book_image
(
    id       bigint generated by default as identity,
    book_id  bigint default null,
    image_id bigint default null
);
create table image
(
    id    bigint generated by default as identity,
    bytes oid,
    name  varchar(255),
    size  int8,
    type  varchar(255),
    primary key (id)
)